[package]
name = "lynn_tcp"
version = "1.0.2"
edition = "2021"
rust-version = "1.83"
authors = ["lynn_tcp Contributors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/cherish-ltt/lynn_tcp"
description = "Lightweight Tcp framework"
categories = ["network-programming"]
keywords = ["tcp" , "tcp-server" , "tcp_client"]

[dependencies]
bytes = "1.9"
tokio = { version = "1", features = ["macros","net","sync","rt-multi-thread","time","io-util"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[features]
default=["server","client"]
server=[]
client=[]
