[package]
name = "lynn_tcp"
version = "1.0.0-rc.2"
edition = "2021"
license = "MIT"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
