[package]
name = "lynn_tcp"
version = "2.0.0-rc.1"
edition = "2024"
rust-version = "1.98.1"
authors = ["lynn_tcp Contributors"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/cherish-ltt/lynn_tcp"
description = "Lightweight asynchronous TCP framework"
categories = ["network-programming"]
keywords = ["tcp" , "tcp-server" , "tcp-client" , "network" , "lynn"]

# 异步运行时
[dependencies]
tokio = { version = "=1.53.1", features = ["macros","net","sync","rt-multi-thread","time","io-util"] }

# 数据结构与并发容器
bytes = "=1.12.1"
crossbeam-deque = "=0.8.7"
dashmap = "=6.2.1"
lazy_static = "=1.5.0"

# 网络与 Socket
socket2 = "=0.6.5"

# 日志追踪
tracing = "=0.1.44"
tracing-subscriber = "=0.3.23"

# 错误处理
thiserror = "=2.0.20"
anyhow = "=1.0.104"

# 指标监控
prometheus = "=0.14.0"

[features]
default=["server","client"]
server=["metrics"]
client=[]

metrics=[]

# 编译优化配置
[profile.dev]
opt-level = 1
[profile.dev.package."*"]
opt-level = 3
